# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

before_install:
  - tlmgr install index

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
